# -*- coding: utf-8 -*-
"""calc_IMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PFHzHtuIp3sRiM5Q3OHmtcy_lTQL8ajV
"""

print('Vamos calcular seu IMC')
nome = input('Digite o seu nome: ')
peso = float(input('Olá, {}! Agora digite seu peso (em Kg, Ex: 68.9): ' .format(nome)))
altura = float(input('Digite sua altura (em m, Ex: 1.80): '))

media = peso / (altura * altura)
print('Seu IMC é: {:.1f}'.format(media))
if media < 18.5:
  print('Você está abaixo do peso ideal para sua altura =/')
elif media > 25:
  print('Você está acima do peso ideal para a sua altura =/')
else:
  print('Você está com o peso ideal para a sua altura! =]')

